
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package layeredimager.analizador.sintactico;

/** CUP generated class containing symbol constants. */
public class UserSym {
  /* terminals */
  public static final int COMMA = 2;
  public static final int error = 1;
  public static final int COLON = 4;
  public static final int SEMI = 3;
  public static final int NAME = 6;
  public static final int EOF = 0;
  public static final int ENTERO = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "COMMA",
  "SEMI",
  "COLON",
  "ENTERO",
  "NAME"
  };
}

