
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package layeredimager.analizador.sintactico;

import layeredimager.model.user.InfoUser;
import java.util.ArrayList;
import java.util.List;
import java_cup.runtime.Symbol;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class UserParser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return UserSym.class;
}

  /** Default constructor. */
  @Deprecated
  public UserParser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public UserParser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public UserParser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\007\000\002\002\005\000\002\002\004\000\002\002" +
    "\004\000\002\003\005\000\002\003\004\000\002\004\005" +
    "\000\002\004\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\014\000\004\010\005\001\002\000\004\005\015\001" +
    "\002\000\004\006\010\001\002\000\004\002\007\001\002" +
    "\000\004\002\000\001\002\000\006\005\ufffd\007\012\001" +
    "\002\000\004\005\ufffe\001\002\000\006\004\013\005\ufffb" +
    "\001\002\000\004\007\012\001\002\000\004\005\ufffc\001" +
    "\002\000\006\002\uffff\010\005\001\002\000\004\002\001" +
    "\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\014\000\006\002\005\003\003\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\004\010\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\004\013\001\001\000\002\001\001\000\006" +
    "\002\015\003\003\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$UserParser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$UserParser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$UserParser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}




    List<InfoUser> infoUsers = new ArrayList();
    List<Integer> idImages = new ArrayList();

    public List<InfoUser> getInfoUsers() {
        return this.infoUsers;
    }

    public void syntax_error(Symbol s) {
        String ss =  (String) s.value;
        StringBuilder descripcion = new StringBuilder("Se esperaba: ");
        expected_token_ids().forEach(x -> descripcion.append(symbl_name_from_id(x)).append(", "));
        System.out.println(ss + " - " + descripcion);
    }



/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$UserParser$actions {
  private final UserParser parser;

  /** Constructor */
  CUP$UserParser$actions(UserParser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$UserParser$do_action_part00000000(
    int                        CUP$UserParser$act_num,
    java_cup.runtime.lr_parser CUP$UserParser$parser,
    java.util.Stack            CUP$UserParser$stack,
    int                        CUP$UserParser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$UserParser$result;

      /* select the action based on the action number */
      switch (CUP$UserParser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // users ::= user SEMI users 
            {
              Object RESULT =null;

              CUP$UserParser$result = parser.getSymbolFactory().newSymbol("users",0, ((java_cup.runtime.Symbol)CUP$UserParser$stack.elementAt(CUP$UserParser$top-2)), ((java_cup.runtime.Symbol)CUP$UserParser$stack.peek()), RESULT);
            }
          return CUP$UserParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= users EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$UserParser$stack.elementAt(CUP$UserParser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$UserParser$stack.elementAt(CUP$UserParser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$UserParser$stack.elementAt(CUP$UserParser$top-1)).value;
		RESULT = start_val;
              CUP$UserParser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$UserParser$stack.elementAt(CUP$UserParser$top-1)), ((java_cup.runtime.Symbol)CUP$UserParser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$UserParser$parser.done_parsing();
          return CUP$UserParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // users ::= user SEMI 
            {
              Object RESULT =null;

              CUP$UserParser$result = parser.getSymbolFactory().newSymbol("users",0, ((java_cup.runtime.Symbol)CUP$UserParser$stack.elementAt(CUP$UserParser$top-1)), ((java_cup.runtime.Symbol)CUP$UserParser$stack.peek()), RESULT);
            }
          return CUP$UserParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // user ::= NAME COLON images 
            {
              Object RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$UserParser$stack.elementAt(CUP$UserParser$top-2)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$UserParser$stack.elementAt(CUP$UserParser$top-2)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$UserParser$stack.elementAt(CUP$UserParser$top-2)).value;
		
            infoUsers.add(new InfoUser(n, idImages));
            idImages = new ArrayList();
         
              CUP$UserParser$result = parser.getSymbolFactory().newSymbol("user",1, ((java_cup.runtime.Symbol)CUP$UserParser$stack.elementAt(CUP$UserParser$top-2)), ((java_cup.runtime.Symbol)CUP$UserParser$stack.peek()), RESULT);
            }
          return CUP$UserParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // user ::= NAME COLON 
            {
              Object RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$UserParser$stack.elementAt(CUP$UserParser$top-1)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$UserParser$stack.elementAt(CUP$UserParser$top-1)).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$UserParser$stack.elementAt(CUP$UserParser$top-1)).value;
		
            infoUsers.add(new InfoUser(n, idImages));
            idImages = new ArrayList();
         
              CUP$UserParser$result = parser.getSymbolFactory().newSymbol("user",1, ((java_cup.runtime.Symbol)CUP$UserParser$stack.elementAt(CUP$UserParser$top-1)), ((java_cup.runtime.Symbol)CUP$UserParser$stack.peek()), RESULT);
            }
          return CUP$UserParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // images ::= ENTERO COMMA images 
            {
              Object RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$UserParser$stack.elementAt(CUP$UserParser$top-2)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$UserParser$stack.elementAt(CUP$UserParser$top-2)).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$UserParser$stack.elementAt(CUP$UserParser$top-2)).value;
		idImages.add(Integer.parseInt(i));
              CUP$UserParser$result = parser.getSymbolFactory().newSymbol("images",2, ((java_cup.runtime.Symbol)CUP$UserParser$stack.elementAt(CUP$UserParser$top-2)), ((java_cup.runtime.Symbol)CUP$UserParser$stack.peek()), RESULT);
            }
          return CUP$UserParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // images ::= ENTERO 
            {
              Object RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$UserParser$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$UserParser$stack.peek()).right;
		String i = (String)((java_cup.runtime.Symbol) CUP$UserParser$stack.peek()).value;
		idImages.add(Integer.parseInt(i));
              CUP$UserParser$result = parser.getSymbolFactory().newSymbol("images",2, ((java_cup.runtime.Symbol)CUP$UserParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$UserParser$stack.peek()), RESULT);
            }
          return CUP$UserParser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$UserParser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$UserParser$do_action(
    int                        CUP$UserParser$act_num,
    java_cup.runtime.lr_parser CUP$UserParser$parser,
    java.util.Stack            CUP$UserParser$stack,
    int                        CUP$UserParser$top)
    throws java.lang.Exception
    {
              return CUP$UserParser$do_action_part00000000(
                               CUP$UserParser$act_num,
                               CUP$UserParser$parser,
                               CUP$UserParser$stack,
                               CUP$UserParser$top);
    }
}

}
