/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package layeredimager.view;

import javax.swing.JMenuItem;
import javax.swing.JPanel;

/**
 *
 * @author asael
 */
public class PrincipalView extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalView
     */
    public PrincipalView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDesk = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        JMenu1 = new javax.swing.JMenu();
        itmCargaCaps = new javax.swing.JMenuItem();
        itmCargaImages = new javax.swing.JMenuItem();
        itmCargaUsers = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        itmAddUser = new javax.swing.JMenuItem();
        itmDeleteUser = new javax.swing.JMenuItem();
        itmEditUser = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        itmAddImage = new javax.swing.JMenuItem();
        itmDelImg = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        itmListImg = new javax.swing.JMenuItem();
        itmTreeCaps = new javax.swing.JMenuItem();
        itmCaps = new javax.swing.JMenuItem();
        itmImgCaps = new javax.swing.JMenuItem();
        itmTreeUsers = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Inter Semi Bold", 0, 56)); // NOI18N
        jLabel1.setText("Layered Imager");

        javax.swing.GroupLayout pnlDeskLayout = new javax.swing.GroupLayout(pnlDesk);
        pnlDesk.setLayout(pnlDeskLayout);
        pnlDeskLayout.setHorizontalGroup(
            pnlDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDeskLayout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(86, 86, 86))
        );
        pnlDeskLayout.setVerticalGroup(
            pnlDeskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDeskLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(jLabel1)
                .addContainerGap(185, Short.MAX_VALUE))
        );

        JMenu1.setText("Carga de datos");

        itmCargaCaps.setText("Cargar capas");
        JMenu1.add(itmCargaCaps);

        itmCargaImages.setText("Cargar imagenes");
        JMenu1.add(itmCargaImages);

        itmCargaUsers.setText("Cargar usuarios");
        JMenu1.add(itmCargaUsers);

        jMenuBar1.add(JMenu1);

        jMenu1.setText("Usuario");

        itmAddUser.setText("Agregar usuario");
        jMenu1.add(itmAddUser);

        itmDeleteUser.setText("Eliminar usuario");
        jMenu1.add(itmDeleteUser);

        itmEditUser.setText("Modificar usuario");
        jMenu1.add(itmEditUser);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Imagenes");

        itmAddImage.setText("Agregar imagen a usuario");
        jMenu2.add(itmAddImage);

        itmDelImg.setText("Eliminar imagen de usuario");
        jMenu2.add(itmDelImg);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Estado de memoria");

        itmListImg.setText("Ver lista de imagenes");
        jMenu3.add(itmListImg);

        itmTreeCaps.setText("Ver arbol de capas");
        jMenu3.add(itmTreeCaps);

        itmCaps.setText("Ver capa");
        jMenu3.add(itmCaps);

        itmImgCaps.setText("Ver imagen y arbol de capas");
        jMenu3.add(itmImgCaps);

        itmTreeUsers.setText("Ver arbol de usuarios");
        jMenu3.add(itmTreeUsers);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlDesk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlDesk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu JMenu1;
    private javax.swing.JMenuItem itmAddImage;
    private javax.swing.JMenuItem itmAddUser;
    private javax.swing.JMenuItem itmCaps;
    private javax.swing.JMenuItem itmCargaCaps;
    private javax.swing.JMenuItem itmCargaImages;
    private javax.swing.JMenuItem itmCargaUsers;
    private javax.swing.JMenuItem itmDelImg;
    private javax.swing.JMenuItem itmDeleteUser;
    private javax.swing.JMenuItem itmEditUser;
    private javax.swing.JMenuItem itmImgCaps;
    private javax.swing.JMenuItem itmListImg;
    private javax.swing.JMenuItem itmTreeCaps;
    private javax.swing.JMenuItem itmTreeUsers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel pnlDesk;
    // End of variables declaration//GEN-END:variables

    public JMenuItem getItmCaps() {
        return itmCaps;
    }

    public JMenuItem getItmCargaCaps() {
        return itmCargaCaps;
    }

    public JMenuItem getItmCargaImages() {
        return itmCargaImages;
    }

    public JMenuItem getItmCargaUsers() {
        return itmCargaUsers;
    }

    public JMenuItem getItmImgCaps() {
        return itmImgCaps;
    }

    public JMenuItem getItmListImg() {
        return itmListImg;
    }

    public JMenuItem getItmTreeCaps() {
        return itmTreeCaps;
    }

    public JMenuItem getItmTreeUsers() {
        return itmTreeUsers;
    }

    public JPanel getPnlDesk() {
        return pnlDesk;
    }    

    public JMenuItem getItmAddImage() {
        return itmAddImage;
    }

    public JMenuItem getItmAddUser() {
        return itmAddUser;
    }

    public JMenuItem getItmDeleteUser() {
        return itmDeleteUser;
    }

    public JMenuItem getItmEditUser() {
        return itmEditUser;
    }

    public JMenuItem getItmDelImg() {
        return itmDelImg;
    }
}
