
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.l2ashdz.layeredimager.analizador.sintactico;

/** CUP generated class containing symbol constants. */
public class ImageSym {
  /* terminals */
  public static final int COMMA = 4;
  public static final int CLOSE_BRACE = 3;
  public static final int error = 1;
  public static final int OPEN_BRACE = 2;
  public static final int EOF = 0;
  public static final int ENTERO = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "OPEN_BRACE",
  "CLOSE_BRACE",
  "COMMA",
  "ENTERO"
  };
}

